language: lua
services:
  - docker

env:
  COMPOSE_VERSION: 18.06

install: 
  - docker-compose build test
  - docker-compose build upload

script: 
  - docker-compose run --rm test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker-compose run --rm upload; fi'

after_script: docker-compose down
