version: '2.1'

services:
  test:
    command: bash -c "luarocks make && busted --shuffle"
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - ".:/lua/"
    working_dir: "/lua"

  lint:
    command: bash -c "luacheck -q ."
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - ".:/lua/"
    working_dir: "/lua"

  upload:
    environment:
      - LUA_ROCKS_API_KEY
    command: bash -c "luarocks install dkjson --local && luarocks upload xml2lua-*.rockspec --force --api-key=$LUA_ROCKS_API_KEY"
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - ".:/lua/"
    working_dir: "/lua"
